Draegerwerk/sdc11073

sdc11073/mdib/statecontainers.py
'en' should be the implied value but not the default value for MdsState/@Lang, might cause Problems with SDC Provider
=> Remove Lang default value and make en an implied value

CHANGELOG.md, sdc11073/namespaces.py, sdc11073/sdcclient/sdcclientimpl.py, sdc11073/sdcclient/subscription.py, sdc11073/sdcdevice/subscriptionmgr.py, tests/test_device_subscriptions.py
... and mandatory attribute IsReferenceParameter
=> Subscriptions using ReferenceParameter 

.github/workflows/build.yml, CHANGELOG.md, codecov.yml, pyproject.toml, tests/test_client_device.py
=> Add codecov to v1

CHANGELOG.md
Add a changelog with fundamental changes since version 1.
#132
=> first changelog for version 2

CHANGELOG.md, src/sdc11073/mdib/containerbase.py, tests/test_descriptorcontainers.py, tests/test_statecontainers.py
- [x I have updated the [changelog](../CHANGELOG.md) accordingly.
=> Fix containerbase.node not set

src/sdc11073/mdib/clientmdib.py
=> bring back age property of RtSampleContainer like in v1.1.x

CHANGELOG.md
=> updated changelog for v1.1.26

CHANGELOG.md, src/sdc11073/commlog.py, src/sdc11073/compression.py, src/sdc11073/mdib/clientmdib.py, src/sdc11073/mdib/containerbase.py, src/sdc11073/mdib/containerproperties.py, src/sdc11073/mdib/descriptorcontainers.py, src/sdc11073/mdib/devicemdib.py, src/sdc11073/mdib/devicewaveform.py, src/sdc11073/mdib/mdibbase.py, src/sdc11073/mdib/msgreader.py, src/sdc11073/mdib/statecontainers.py, src/sdc11073/observableproperties/observables.py, src/sdc11073/pmtypes.py, src/sdc11073/pysoap/soapclient.py, src/sdc11073/pysoap/soapenvelope.py, src/sdc11073/roles/alarmprovider.py, src/sdc11073/sdcclient/hostedservice.py, src/sdc11073/sdcclient/operations.py, src/sdc11073/sdcclient/sdcclientimpl.py, src/sdc11073/sdcdevice/exceptions.py, src/sdc11073/sdcdevice/httpserver.py, src/sdc11073/sdcdevice/intervaltimer.py, src/sdc11073/sdcdevice/sco.py, src/sdc11073/sdcdevice/sdc_handlers.py, src/sdc11073/sdcdevice/sdcdeviceimpl.py, src/sdc11073/sdcdevice/sdcservicesimpl.py, src/sdc11073/sdcdevice/subscriptionmgr.py, src/sdc11073/xmlparsing.py, tests/test_mdib.py
=> fix nsmap bug

CHANGELOG.md, src/sdc11073/provider/sco.py
=> fixed unneeded cration of operation target states by role provider.

CHANGELOG.md
=> Adapt the changelog for the release 1.2.0

.github/workflows/build.yml, pyproject.toml, tests/base_test.py, tests/test_alertsignaldelegate.py, tests/test_client_device.py, tests/test_compression.py, tests/test_device.py, tests/test_device_services.py, tests/test_discovery.py, tests/test_tutorial.py, tests/utils.py
=> make unittest parallelize

CHANGELOG.md, src/sdc11073/consumer/consumerimpl.py
=> 228 get adapter containing ip can fail if target address is in a different subnet

.github/workflows/publish.yml
=> fix zipping unittest results in release

CHANGELOG.md
=> Update for release 1.2.1

CHANGELOG.md, src/sdc11073/sdcdevice/sdcdeviceimpl.py
=> expose the http_server_timeout parameter on the SdcDevice interface

CHANGELOG.md
=> add version 1.3.0 to the changelog

.github/workflows/build.yml, CHANGELOG.md, codecov.yml, pyproject.toml
=> Modify python versions

CHANGELOG.md, src/sdc11073/roles/alarmprovider.py
=> alert provider role sends self check one second before time elapsed.

CHANGELOG.md, src/sdc11073/consumer/consumerimpl.py, src/sdc11073/consumer/serviceclients/stateeventservice.py, src/sdc11073/provider/porttypes/stateeventserviceimpl.py, src/sdc11073/xml_types/actions.py, src/sdc11073/xml_types/msg_types.py, tests/test_alertsignaldelegate.py, tests/test_client_device.py, tests/test_compression.py, tests/test_device.py, tests/test_device_periodic_reports.py, tests/test_operations.py, tests/test_string_enum_descriptors.py, tests/test_tutorial.py, tutorial/consumer/consumer.py
=> handling of SystemErrorReport implemented

CHANGELOG.md, src/sdc11073/mdib/containerbase.py
=> change default in mk_copy

CHANGELOG.md
=> Update date of release v1.3.1

src/sdc11073/namespaces.py, src/sdc11073/roles/product.py
Fix namespace definition and logger debug message
=> Fix namespace definition v2

CHANGELOG.md, src/sdc11073/mdib/statecontainers.py, src/sdc11073/xml_types/pm_types.py, tests/test_statecontainers.py
=> Implement MetricValue for DistributionSampleArrayMetricState

CHANGELOG.md
Preparation for alpha package 2.0.0a7
=> Preparation for alpha package 2.0.0a7

CHANGELOG.md, src/sdc11073/mdib/containerproperties.py, tests/test_pmtypes.py
=> fix instance comparison of extensions

CHANGELOG.md, src/sdc11073/wsdiscovery.py
=> added xml header to wsdiscovery soap messages

CHANGELOG.md, examples/ReferenceTest/test_reference.py, src/sdc11073/consumer/consumerimpl.py, src/sdc11073/consumer/subscription.py, tests/test_client_device.py
=> bug: isConnected may be missleading 

CHANGELOG.md, src/sdc11073/xml_types/pm_types.py
- [x Bug fix (non-breaking change which fixes an issue)
=> fixed wrong typing in LocalizedText constructor

CHANGELOG.md, src/sdc11073/roles/alarmprovider.py, src/sdc11073/roles/audiopauseprovider.py, tests/test_operations.py
=> fixed possible caching errors in AlarmProvider and AudioPauseProvider

CHANGELOG.md, src/sdc11073/sdcclient/sdcclientimpl.py, src/sdc11073/sdcclient/subscription.py
=> fix isConnected bug

CHANGELOG.md, src/sdc11073/wsdiscovery/wsdimpl.py
=> fix runtime error

CHANGELOG.md, src/sdc11073/mdib/mdibbase.py, src/sdc11073/mdib/transactions.py, tests/test_transaction.py
=> fixed problems in DescriptorTransaction

CHANGELOG.md, src/sdc11073/mdib/mdibbase.py, tests/mockstuff.py, tests/test_client_device.py
=> fix inconsistent InstanceId in GetMdibResponse

CHANGELOG.md, src/sdc11073/mdib/consumermdib.py, tests/test_client_device.py
=> fixed possible exception in ConsumerMdib._get_context_states

CHANGELOG.md, src/sdc11073/mdib/containerbase.py, tests/test_client_device.py, tests/test_statecontainers.py
=> use math.isclose in ContainerBase.diff

CHANGELOG.md
=> edit changelog

CHANGELOG.md, src/sdc11073/mdib/descriptorcontainers.py
=> fixed DescriptorContainer.node not updated

.github/workflows/build.yml, CHANGELOG.md, src/sdc11073/multikey.py
=> use lock in mutikey getOne and get methods

CHANGELOG.md, src/sdc11073/xml_types/pm_types.py
=> fix ClinicalInfo.RelatedMeasurement data type.

CHANGELOG.md, examples/ReferenceTest/reference_provider.py, src/sdc11073/commlog.py, src/sdc11073/pysoap/msgfactory.py, src/sdc11073/wsdiscovery/networkingthread.py, src/sdc11073/wsdiscovery/wsdimpl.py, tests/test_comm_logger.py, tests/test_discovery.py
=> improve threading of wsdiscovery sending and receiving

CHANGELOG.md, src/sdc11073/consumer/serviceclients/setservice.py, tests/test_operations.py
- [x Bug fix (non-breaking change which fixes an issue)
=> fixed SetServiceClient.set_numeric_value accepted numeric data types.

CHANGELOG.md, src/sdc11073/xml_types/xml_structure.py, tests/test_pmtypes.py
=> fixed ElementWithTextList if node.text is None

CHANGELOG.md
=> add release info to changelog

CHANGELOG.md, src/sdc11073/loghelper.py, tests/test_loghelper.py
=> allow any type for log prefix v1

CHANGELOG.md, src/sdc11073/loghelper.py, tests/test_loghelper.py
=> allow any type for log prefix

pyproject.toml
=> add rules and increase version of ruff

pyproject.toml
=> added missing classifier

CHANGELOG.md, src/sdc11073/wsdiscovery/common.py, src/sdc11073/wsdiscovery/networkingthread.py, src/sdc11073/wsdiscovery/wsdimpl.py, tests/test_discovery.py
=> add multicast ttl to wsdiscovery

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CHANGELOG.md, pyproject.toml, src/sdc11073/schema_resolver.py, tests/test_schema_validator.py
=> fix schema validation error on unix
